import React from "react";
import Page from "../../components/Pages.tsx";

const Webs = () => {
    const description = 'portfolio of my created websites'

    const content = 
      <div className="relative space-y-5 text-gray-800">
        
        <p>
         I never thought I'd be into web development, yet here we are. The very website you're on now was created
         using <b>Typescript</b>, <b>Tailwind</b>, and <b>REACT</b>, which is the framework I've used on most of my sites.
         Apart from some interesting elements such as the animated text you see, it's worth pointing out that this <b>
         background</b> is not an image. It's in fact dynamically generated byusing <b>Bayer dithering</b>, which uses a 
         small repeating pattern to gently break up solid colors, making up the grainy blue you see here.
        </p>

        <p>
         Apart from my own portfolio website, I also helped out some friends by developing their sites. You can check them out below,
         click on them to go to the actual site:
        </p>

        <div className="flex flex-col flex-wrap space-y-8 pt-2">
            <div className="w-full flex flex-col md:flex-row items-start md:space-x-5">
                <a href="https://juliaoprzondek.uk" className="w-full md:w-3/5 object-cover hover:shadow-lg transition-all" target="_blank">
                    <img
                        src="/images/julia_o.png"
                        alt="Julia's website"
                        className="rounded-lg"
                    />
                </a>
                <div className="w-full pt-4 md:pt-0 md:w-2/3">
                    <p className="font-semibold pb-4">Julia Oprzondek</p>
                    <p>
                        Made for my communications/arts friend, I wanted it to show a quirky and artistic side. We set on a simple but 
                        splashy color scheme with a clear action message and aesthetic project pages. 
                    </p>
                </div>
            </div>

            <div className="w-full flex flex-col md:flex-row items-start md:space-x-5">
                <a href="https://tomaszgola.eu" className="w-full md:w-3/5 object-cover hover:shadow-lg transition-all" target="_blank">
                    <img
                        src="/images/tomasz_g.png"
                        alt="Tomek's website"
                        className="rounded-lg"
                    />
                </a>
                <div className="w-full pt-4 md:pt-0 md:w-2/3">
                    <p className="font-semibold pb-4">Tomasz Gola</p>
                    <p>
                        A more academic look for my PhD friend. Showcases a list of articles with a single-page approach. It's got 
                        some smooth animations and looks nice on a phone!
                    </p>
                </div>
            </div>

            <div className="w-full flex flex-col md:flex-row items-start md:space-x-5">
                <a href="https://dash.klereearth.uk/" className="w-full md:w-3/5 object-cover hover:shadow-lg transition-all" target="_blank">
                    <img
                        src="/images/platform.png"
                        alt="Klere dashboard"
                        className="rounded-lg"
                    />
                </a>
                <div className="w-full pt-4 md:pt-0 md:w-2/3">
                    <p className="font-semibold pb-4">Klere Dashboard</p>
                    <p>
                        Klere's dashboard for integrated nature and carbon footprints. This is the most sophisticated site, 
                        with a fully developed backend and authentication processes.
                    </p>
                </div>
            </div>

            <div className="w-full flex flex-col md:flex-row items-start md:space-x-5">
            <div className="w-full md:w-3/5 object-cover hover:shadow-lg transition-all" >
                    <img
                        src="/images/olympics.png"
                        alt="Olympic bets website"
                        className="rounded-lg"
                    />
                </div>
                <div className="w-full pt-4 md:pt-0 md:w-2/3">
                    <p className="font-semibold pb-4">Olympics Bets</p>
                    <p>
                        I made a site for my friends and I to bet on the olympics! It had all the flags and icons 
                        for each country, and kept track of everyone's bets and results over time. 
                    </p>
                </div>
            </div>

        </div>

      </div>

    return (
      <Page title={"web development"} description={description} content={content} dates={"2024"} page='projects'     />

    );
  };
  
export default Webs